[package]
name = "data-encoding-bin"
version = "0.3.1"
authors = ["Julien Cretin <git@ia0.eu>"]
license = "MIT"
edition = "2021"
keywords = ["base-conversion", "encoding", "base64", "base32", "hex"]
categories = ["command-line-utilities", "encoding"]
readme = "README.md"
repository = "https://github.com/ia0/data-encoding"
description = "Swiss Army knife for data-encoding"
include = ["Cargo.toml", "LICENSE", "README.md", "src/main.rs"]

[[bin]]
name = "data-encoding"
path = "src/main.rs"

[dependencies]
data-encoding = { version = "2", path = "../lib" }
getopts = "0.2"
